name: Making pyxapp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install SDL2 library
      run: |
        sudo apt-get update
        sudo apt-get install -y libsdl2-dev
        
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyxel  # Pyxelの追加
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Make pyxapp
      run: |
        pyxel package icecream icecream/__main__.py
        
    - name: Upload artifact for deployment
      uses: actions/upload-artifact@v4
      with:
        name: place-app
        path: icecream.pyxapp  # ビルドされたアプリのパスを指定
